### ISSUE TITLE
Emulate keypad on canchecked display

### ISSUE THREAD

**Issue by Scotty2233** [analoghan/haltech_keypad_emulator#4]
Hi there,

I have a canchecked MFD28 touchscreen can display paired to a Haltech ECU.
The canchecked display has the ability to have on screen can switches but no support for Haltech currently.
So that got me thinking if I can emulate a keypad like you have done here, that could make it work.
Ideally I would emulate a 2x4 keypad as the display has 8 can switching outputs. I am working with the manufacturer to test this out and require CanID's, bytes, and values the keypad outputs.
The display handles all can transmitting, so no need for Arduino or code.

Any help would be much appreciated
Thanks, Scott

**Comment by analoghan** [comment]
Hi Scott,

I don't have a 2x4 keypad to use to pull the CAN settings.  I believe Tolunay Gul did some work on this though.  See here:  https://github.com/tolunaygul/haltech_keypad_emulator_inputs

**Comment by jblazeg** [comment]
> Hi there,
> 
> I have a canchecked MFD28 touchscreen can display paired to a Haltech ECU. The canchecked display has the ability to have on screen can switches but no support for Haltech currently. So that got me thinking if I can emulate a keypad like you have done here, that could make it work. Ideally I would emulate a 2x4 keypad as the display has 8 can switching outputs. I am working with the manufacturer to test this out and require CanID's, bytes, and values the keypad outputs. The display handles all can transmitting, so no need for Arduino or code.
> 
> Any help would be much appreciated Thanks, Scott

Haltech support is now implemented in MFD28

**Comment by jblazeg** [comment]
You can set the display to support Haltech IOA or IOB, which sends the 4 analogue inputs and 4 switches over can bus. Use firmware 4.100h or newer
